export const data = {
  messages: [
    {
      _id: 1,
      profile: "images/signup.jpg",
      image: "",
      username: "Test",
      message: "Hello there!",
      to: "Tests",
      from: "Test",
      type: "one",
    },
    {
      _id: 2,
      profile: "images/signup.jpg",
      image: "images/signup.jpg",
      username: "Test",
      message: "Hello there!",
      to: "Tests",
      from: "Test",
      type: "one",
    },
    {
      _id: 3,
      profile: "images/signup.jpg",
      image: "images/signup.jpg",
      username: "Tests",
      message: "Hello",
      to: "Tests",
      from: "Test",
      type: "two",
    },
    {
      _id: 4,
      profile: "images/signup.jpg",
      image: "",
      username: "Test",
      message: "WassupBro!",
      to: "Test",
      from: "Tests",
      type: "one",
    },
  ],
};
